name: Push/PR Check

on:
  - push
  - pull_request

jobs:
  buildcheck:
    name: Build check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: Run vet
      run: | 
        go vet .
    - name: Run tests
      run: | 
        go test -race -v .
